services:
  - type: web
    name: Taqwa
    runtime: docker
    plan: free
    dockerfilePath: Dockerfile
    envVars:
      - key: PORT
        value: "10000"
      - key: DATABASE_URL
        value: postgresql://taqwa_uz_user:5Y5JlQ0XvpgMRbuvx08EOjWViIMRuGVq@dpg-d9hhab37uimc73f93p00-a.oregon-postgres.render.com/taqwa_uz
      - key: DB_USER
        value: taqwa_uz_user
      - key: DB_PASS
        value: 5Y5JlQ0XvpgMRbuvx08EOjWViIMRuGVq
      - key: WEATHER_API_KEY
        value: 4809559fb3f3e5bc2b87f0f07f3d127f
