server.port=2026
spring.datasource.url=jdbc:postgresql://localhost:5432/misbahul_db
spring.datasource.username=postgres
spring.datasource.password=root1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

weather.api.key=4809559fb3f3e5bc2b87f0f07f3d127f
weather.api.url=https://api.openweathermap.org/data/2.5